services:
  bind9:
    # https://hub.docker.com/r/internetsystemsconsortium/bind9
    image: internetsystemsconsortium/bind9:9.18
    ports: 
      - 53:53/tcp
      - 53:53/udp
      - 953:953/tcp
    networks:
      - dns
    volumes:
      - type: bind
        source: ./docker/etc/bind/named.conf
        target: /etc/bind/named.conf
      - type: bind
        source: ./docker/var/lib/bind/db.exxampled.com
        target: /var/lib/bind/db.exxampled.com
      - type: bind
        source: ./docker/var/lib/bind/db.xn--fa-hia.de.
        target: /var/lib/bind/db.xn--fa-hia.de.
networks:
  dns:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.0.2.0/24
        - subnet: 2001:db8::/32
